import {
  Apple,
  Bike,
  Book,
  BookOpen,
  Brain,
  Briefcase,
  Clock,
  Code,
  Coffee,
  Dumbbell,
  Flower,
  Folder,
  Footprints,
  Gamepad2,
  GlassWater,
  GraduationCap,
  Heart,
  HeartPulse,
  Laptop,
  Leaf,
  Medal,
  Microscope,
  Moon,
  Mountain,
  Music,
  Palette,
  PawPrint,
  Pencil,
  PenLine,
  PenTool,
  Phone,
  Presentation,
  Salad,
  Smile,
  SmilePlus,
  Sparkles,
  Sprout,
  Star,
  Sun,
  Swords,
  Target,
  Timer,
  Trees,
  Users,
  Wallet,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  apple: Apple,
  bike: Bike,
  book: Book,
  "book-open": BookOpen,
  brain: Brain,
  briefcase: Briefcase,
  clock: Clock,
  code: Code,
  coffee: Coffee,
  dumbbell: Dumbbell,
  flower: Flower,
  folder: Folder,
  footprints: Footprints,
  gamepad: Gamepad2,
  "glass-water": GlassWater,
  "graduation-cap": GraduationCap,
  heart: Heart,
  "heart-pulse": HeartPulse,
  laptop: Laptop,
  leaf: Leaf,
  medal: Medal,
  microscope: Microscope,
  moon: Moon,
  mountain: Mountain,
  music: Music,
  palette: Palette,
  "paw-print": PawPrint,
  pencil: Pencil,
  "pen-line": PenLine,
  "pen-tool": PenTool,
  phone: Phone,
  presentation: Presentation,
  salad: Salad,
  smile: Smile,
  "smile-plus": SmilePlus,
  sparkles: Sparkles,
  sprout: Sprout,
  star: Star,
  sun: Sun,
  swords: Swords,
  target: Target,
  timer: Timer,
  trees: Trees,
  users: Users,
  wallet: Wallet,
  zap: Zap,
};

const DEFAULT_ICON: LucideIcon = Star;

export function getHabitIcon(name: string | null | undefined): LucideIcon {
  if (!name) return DEFAULT_ICON;
  return ICON_MAP[name] ?? DEFAULT_ICON;
}

export function isHabitIconName(name: string | null | undefined): boolean {
  return !!name && name in ICON_MAP;
}
